### PR TITLE
fix dealer problems

### LINKED ISSUE #12: dealer problem
- dealer has to be private
- dealer is an integer

### PR DESCRIPTION
**Pull request by bleikerja**
- dealer gets handled as index in class but player gets returned 

closes #12

### CODE REVIEW

File: src/main/kotlin/hwr/oop/group1/poker/Game.kt [hunk 1]
```diff
@@ -1,23 +1,25 @@
...
         players += player
     }
 
-    fun nextDealer() {
-        dealer = (dealer + 1) % players.size
+    private fun nextDealer() {
+        dealerPosition = (dealerPosition + 1) % players.size
     }
 
     fun newRound() {
```
Comment (twittke) [inline src/main/kotlin/hwr/oop/group1/poker/Game.kt:17]: I think, this doesn't need to be public, because no one calls it from outside.
A new round starts 
1) at the beginning of a new game and 
2) when the previous round has ended, but the game hasn't.

But I'm also fine with changing it, when we implement this logic.

**Review by twittke — APPROVED** [review]

**Review by mic-litz — APPROVED** [review]
- dealer fix in #21

**Review by mic-litz — APPROVED** [review]
all good!
